### ISSUE TITLE
Issue using the API

### ISSUE THREAD

**Issue by TREEMIUM** [arthuRHD/immosheets#107]
Hi,

Thanks for your API.

I do not understand, I am putting zip_codes but I still have this error using SeLogerSearchQuery:

Field required [type=missing, input_value={'zip_codes': '75001', 'm...': None, 'sortBy': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.3/v/missing

Has it happened to somebody? If yes how can I resolve it?

Thanks!

Raphaël

**Comment by arthuRHD** [comment]
Hi, do you still encounter this issue ?
