### ISSUE TITLE
Add a software licence

### ISSUE THREAD

**Issue by arthuRHD** [arthuRHD/immosheets#22]
Determine which licence suits the best.

**Comment by anushkabishnoi** [comment]
Hello, this is my first experience with open source contributions. Would really appreciate it if you explained exactly what is needed to be done.

I would love to work on this issue.

Thanks in advance! :)

**Comment by arthuRHD** [comment]
Currently, this project has no licence. It would be cool if you can add one.

Here's a documentation from GitHub itself which describes how it can be done: 
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Feel free to ask questions if needed. ;)

**Comment by anushkabishnoi** [comment]
Hi @arthuRHD ! Thanks for assigning me :)

So I researched licenses a bit, and I'm thinking along the lines of Apache 2.0. We can also go with MIT if you want. (Apache's really long and complicated, but its also recommended for business, and contribution purposes, plus it's the popular choice in open-source).

Also if you could help me out with the packages used, thanks again!
