### ISSUE TITLE
Improving README.md 

### ISSUE THREAD

**Issue by the-amazing-atharva** [arthuRHD/immosheets#23]
Hey @arthuRHD 

I am a beginner here and came across this repository while searching for issues labelled documentation.

I think that by aligning the logo and the tagline, badges to the center - the README.md would look better

I also would like to add a description paragraph for the project.

If you are ok with the above suggestions, could you assign me to the issue and let me work on the README.md?

Regards!!!

**Comment by arthuRHD** [comment]
Hi @the-amazing-atharva , You're more than welcomed to do so. Feel free to contribute 👍🏻

**Comment by the-amazing-atharva** [comment]
Thanks!!!

Looking forward to sending a PR
